FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

LABEL name="ubi8-minimal" \
      vendor="Sumo Logic" \
      version="8.4" \
      release="1" \
      summary="Provides the latest release of the minimal Red Hat Universal Base Image 8." \
      description="The Universal Base Image Minimal is a stripped down image that uses microdnf as a package manager." \
      maintainer="collection@sumologic.com"

ADD https://www.apache.org/licenses/LICENSE-2.0.txt \
    /licenses/LICENSE
