name: Build images

on:
  # run this job every Monday at 9 am UTC
  schedule:
    - cron: "0 9 * * 1"

jobs:
  build-all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        run: make build-all
