name: PRs checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-all:
    runs-on: ubuntu-22.04
    env:
      CHECK: "true"
      PYAXIS_API_TOKEN: ${{ secrets.RED_HAT_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        run: make build-all
