name: Manual run

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Action to perform
        options:
          - "build"
          - "push"
          - "check"
          - "certify"
      force:
        type: choice
        description: Perform action even if image already exists
        options:
          - "false"
          - "true"
      name:
        description: Image name
        required: true
        type: string
      version:
        description: Image version
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ACTION: "${{ inputs.action }}"
      FORCE: "${{ inputs.force }}"
      NAME: "${{ inputs.NAME }}"
      VERSION: "${{ inputs.VERSION }}"
      PYAXIS_API_TOKEN: ${{ secrets.RED_HAT_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Open Source ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Get preflight
        run: make install_preflight
      - name: Build push
        run: |
          BIN=./bin/ \
          PYAXIS_API_TOKEN="${PYAXIS_API_TOKEN=}" \
          ACTION="${ACTION}" \
          NAME="${NAME}" \
          VERSION="${VERSION}" \
          FORCE="${FORCE}" \
          ./scripts/build-push.sh
