name: Manual test run

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PUSH: "true"
      CHECK: "true"
      CERTIFY: "true"
      FORCE: "true"
      NAME: opentelemetry-operator
      VERSION: "0.95.0"
      PYAXIS_API_TOKEN: ${{ secrets.RED_HAT_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Open Source ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Get preflight
        run: |
          curl -LO https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/latest/download/preflight-linux-amd64
          chmod +x preflight-linux-amd64
          mv preflight-linux-amd64 /usr/local/bin/preflight
      - name: Build push
        run: |
          PYAXIS_API_TOKEN="${PYAXIS_API_TOKEN=}" \
          NAME="${NAME}" \
          VERSION="${VERSION}" \
          CHECK="${CHECK}" \
          PUSH="${PUSH}" \
          FORCE="${FORCE}" \
          CERTIFY="${CERTIFY}" \
          ./scripts/build-push.sh
